[workspace]
authors = ["[Adele Jordan] <[ajae2021@mymail.pomona.edu]>"]
channels = ["conda-forge"]
name = "Python-Practice--MMA-"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
pandas = ">=2.3.0,<3"
matplotlib = ">=3.10.3,<4"
pip = ">=25.1.1,<26"
ioos_qc = ">=2.2.0,<3"


